version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

workdir: &workdir /tmp/woodchuck

commands:
  deploy_destination_to_region:
    parameters:
      region:
        type: string
      destination:
        type: string
      arch:
        type: string
    steps:
      - run:
          name: deploy <<parameters.region>> <<parameters.destination>> <<parameters.arch>>
          command: |
            RESULT=$(aws lambda publish-layer-version --layer-name woodchuck_<<parameters.destination>>_<<parameters.arch>> --zip-file "fileb://extensions.zip" --region <<parameters.region>> --compatible-architectures <<parameters.arch>>)
            VERSION=$(echo $RESULT | jq '.Version')
            aws lambda add-layer-version-permission --layer-name woodchuck_<<parameters.destination>>_<<parameters.arch>> --region <<parameters.region>> --statement-id "public-layer" --version-number $VERSION --action lambda:GetLayerVersion --principal '*'

jobs:
  test:
    working_directory: *workdir
    docker:
      - image: ekidd/rust-musl-builder:latest
    steps:
      - attach_workspace:
          at: *workdir
      - checkout
      - run:
          name: test
          command: |
            cargo test
  build_x86_64:
    working_directory: *workdir
    parameters:
      destination:
        type: string
      arch:
        type: string
    docker:
      - image: ekidd/rust-musl-builder:latest
    steps:
      - attach_workspace:
          at: *workdir
      - checkout
      - run:
          name: build
          command: |
            cargo build --features "<<parameters.destination>>" --release
            mkdir destination_<<parameters.destination>>_<<parameters.arch>> && 
            mkdir destination_<<parameters.destination>>_<<parameters.arch>>/extensions &&
            cp target/x86_64-unknown-linux-musl/release/woodchuck destination_<<parameters.destination>>_<<parameters.arch>>/extensions/woodchuck_<<parameters.destination>>_<<parameters.arch>>
      - save_cache:
          name: "Saving repository cache for {{ .Branch }} {{ .Revision }} <<parameters.destination>>"
          key: repo-cache-{{ .Branch }}-{{ .Revision }}-<<parameters.destination>>_<<parameters.arch>>
          paths:
            - destination_<<parameters.destination>>_<<parameters.arch>>
            - package.sh
            - deploy.sh

  build_arm64:
    working_directory: *workdir
    parameters:
      destination:
        type: string
      arch:
        type: string
    docker:
      - image: messense/rust-musl-cross:aarch64-musl
    steps:
      - attach_workspace:
          at: *workdir
      - checkout
      - run:
          name: build
          command: |
            cargo build --features "<<parameters.destination>> <<parameters.arch>>" --release
            mkdir destination_<<parameters.destination>>_<<parameters.arch>> && 
            mkdir destination_<<parameters.destination>>_<<parameters.arch>>/extensions &&
            cp target/aarch64-unknown-linux-musl/release/woodchuck destination_<<parameters.destination>>_<<parameters.arch>>/extensions/woodchuck_<<parameters.destination>>_<<parameters.arch>>
      - save_cache:
          name: "Saving repository cache for {{ .Branch }} {{ .Revision }} <<parameters.destination>>"
          key: repo-cache-{{ .Branch }}-{{ .Revision }}-<<parameters.destination>>_<<parameters.arch>>
          paths:
            - destination_<<parameters.destination>>_<<parameters.arch>>
            - package.sh
            - deploy.sh

  deploy:
    working_directory: *workdir
    parameters:
      destination:
        type: string
      arch:
        type: string
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: *workdir
      - restore_cache:
          keys:
            - repo-cache-{{ .Branch }}-{{ .Revision }}-<<parameters.destination>>_<<parameters.arch>>
      - aws-cli/setup
      - run:
          name: package
          command: |
            ./package.sh <<parameters.destination>> <<parameters.arch>>
      - deploy_destination_to_region:
          region: "eu-west-1"
          destination: <<parameters.destination>>
          arch: <<parameters.arch>>
      - deploy_destination_to_region:
          region: "eu-west-2"
          destination: <<parameters.destination>>
          arch: <<parameters.arch>>
      - deploy_destination_to_region:
          region: "eu-central-1"
          destination: <<parameters.destination>>
          arch: <<parameters.arch>>
      - deploy_destination_to_region:
          region: "us-east-1"
          destination: <<parameters.destination>>
          arch: <<parameters.arch>>
      - deploy_destination_to_region:
          region: "us-west-2"
          destination: <<parameters.destination>>
          arch: <<parameters.arch>>
      - deploy_destination_to_region:
          region: "us-east-2"
          destination: <<parameters.destination>>
          arch: <<parameters.arch>>

workflows:
  workflow:
    jobs:
      - test
      - build_x86_64:
          destination: loggly
          arch: x86_64
          name: build_loggly_x86_64
          requires:
            - test
      - release_loggly_x86_64:
          type: approval
          requires:
            - build_loggly_x86_64
          filters:
            branches:
              only:
                - main
      - deploy:
          destination: loggly
          arch: x86_64
          requires:
            - release_loggly_x86_64
      - build_x86_64:
          destination: logzio
          arch: x86_64
          name: build_logzio_x86_64
          requires:
            - test
      - release_logzio_x86_64:
          type: approval
          requires:
            - build_logzio_x86_64
          filters:
            branches:
              only:
                - main
      - deploy:
          destination: logzio
          arch: x86_64
          requires:
            - release_logzio_x86_64
      - build_arm64:
          destination: loggly
          arch: arm64
          name: build_loggly_arm64
          requires:
            - test
      - release_loggly_arm64:
          type: approval
          requires:
            - build_loggly_arm64
          filters:
            branches:
              only:
                - main
      - deploy:
          destination: loggly
          arch: arm64
          requires:
            - release_loggly_arm64
      - build_arm64:
          destination: logzio
          arch: arm64
          name: build_logzio_arm64
          requires:
            - test
      - release_logzio_arm64:
          type: approval
          requires:
            - build_logzio_arm64
          filters:
            branches:
              only:
                - main
      - deploy:
          destination: logzio
          arch: arm64
          requires:
            - release_logzio_arm64
