version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.1

workdir: &workdir /tmp/woodchuck

commands:
  deploy_destination_to_region:
    parameters:
      region:
        type: string
      destination:
        type: string
    steps:
      - run:
          name: deploy <<parameters.region>> <<parameters.destination>>
          command: |
            RESULT=$(aws lambda publish-layer-version --layer-name woodchuck_<<parameters.destination>> --zip-file "fileb://extensions.zip" --region <<parameters.region>>)
            VERSION=$(echo $RESULT | jq '.Version')
            aws lambda add-layer-version-permission --layer-name woodchuck_<<parameters.destination>> --region <<parameters.region>> --statement-id "public-layer" --version-number $VERSION --action lambda:GetLayerVersion --principal '*'

jobs:
  test:
    working_directory: *workdir
    docker:
      - image: ekidd/rust-musl-builder:latest
    steps:
      - attach_workspace:
          at: *workdir
      - checkout
      - run:
          name: test
          command: |
            cargo test
  build:
    working_directory: *workdir
    parameters:
      destination:
        type: string
    docker:
      - image: ekidd/rust-musl-builder:latest
    steps:
      - attach_workspace:
          at: *workdir
      - checkout
      - run:
          name: build
          command: |
            cargo build --features <<parameters.destination>> --release &&
            mkdir extensions &&
            cp target/x86_64-unknown-linux-musl/release/woodchuck extensions/woodchuck_<<parameters.destination>>
      - save_cache:
          name: "Saving repository cache for {{ .Branch }} {{ .Revision }} <<parameters.destination>>"
          key: repo-cache-{{ .Branch }}-{{ .Revision }}-<<parameters.destination>>
          paths:
            - extensions

  deploy:
    working_directory: *workdir
    parameters:
      destination:
        type: string
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: *workdir
      - restore_cache:
          keys:
            - repo-cache-{{ .Branch }}-{{ .Revision }}-<<parameters.destination>>
      - aws-cli/setup
      - run:
          name: package
          command: |
            zip -r extensions.zip extensions
      - deploy_destination_to_region:
          region: "eu-west-1"
          destination: <<parameters.destination>>
      - deploy_destination_to_region:
          region: "eu-west-2"
          destination: <<parameters.destination>>
      - deploy_destination_to_region:
          region: "eu-west-3"
          destination: <<parameters.destination>>
      - deploy_destination_to_region:
          region: "eu-central-1"
          destination: <<parameters.destination>>
      - deploy_destination_to_region:
          region: "eu-north-1"
          destination: <<parameters.destination>>
      - deploy_destination_to_region:
          region: "us-east-1"
          destination: <<parameters.destination>>
      - deploy_destination_to_region:
          region: "us-west-1"
          destination: <<parameters.destination>>
      - deploy_destination_to_region:
          region: "us-west-2"
          destination: <<parameters.destination>>
      - deploy_destination_to_region:
          region: "us-east-2"
          destination: <<parameters.destination>>
      - deploy_destination_to_region:
          region: "ca-central-1"
          destination: <<parameters.destination>>

workflows:
  workflow:
    jobs:
      - test
      - build:
          destination: loggly
          name: build_loggly
          requires:
            - test
          filters:
            branches:
              only:
                - main
      - release:
          type: approval
          requires:
            - build_loggly
      - deploy:
          destination: loggly
          requires:
            - release
      - build:
          destination: logzio
          name: build_logzio
          requires:
            - test
          filters:
            branches:
              only:
                - main
      - release:
          type: approval
          requires:
            - build_logzio
      - deploy:
          destination: logzio
          requires:
            - release
